---
- name: Handlers Example
  hosts: serverb
  gather_facts: false
  tasks:
    - name: Install httpd latest version
      yum:
        name: httpd
        state: latest
      become: true
      notify: restart_httpd  # 해당 테스크의 changed 상태가 발견 되었을때 notify가 트리거 되어 핸들러가 실행

  handlers:
    - name: restart_httpd
      become: true
      service:
        name: httpd
        state: started
